// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_List = require("bs-platform/lib/js/belt_List.js");

var render = ((htmlString) => document.body.insertAdjacentHTML("beforeend", htmlString));

function jsxToHtml(tagName, children, param) {
  var c = Belt_List.reduce(children, "", (function (a, b) {
          return a + b;
        }));
  return "<" + tagName + ">" + c + "</" + tagName + ">";
}

function p(param, param$1) {
  return jsxToHtml("p", param, param$1);
}

function div(param, param$1) {
  return jsxToHtml("div", param, param$1);
}

function main(param, param$1) {
  return jsxToHtml("main", param, param$1);
}

exports.render = render;
exports.jsxToHtml = jsxToHtml;
exports.p = p;
exports.div = div;
exports.main = main;
/* No side effect */
