// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Sinuous = require("sinuous");

function h(prim, prim$1, prim$2) {
  return Sinuous.h(prim, prim$1, prim$2);
}

exports.h = h;
/* sinuous Not a pure module */
